### ISSUE TITLE
Definir diseño inicial

### ISSUE THREAD

**Issue by andres174** [gabriel12QK/movil-Ecommerce#1]
- Definir colores
- Logo
- Directrices para el diseño en móvil

**Comment by Arqui9897** [comment]
[Branding DELI GO by Alex Arqui.pdf](https://github.com/gabriel12QK/movil-Ecommerce/files/10172111/Branding.DELI.GO.by.Alex.Arqui.pdf)
![Branding DELI GO by Alex Arqui](https://user-images.githubusercontent.com/87206394/206069080-9986da8b-caa8-4683-bec5-43ea6d84412d.png)
