### ISSUE TITLE
Ver productos por categoría

### ISSUE THREAD

**Issue by andres174** [gabriel12QK/movil-Ecommerce#11]
Tomando como guía el branding disponible en la carpeta compartida de drive, crear la pagina de VER PRODUCTOS POR CATEGORÍA con las funcionalidades requeridas.

https://drive.google.com/file/d/1gmLzmyjGCvgnsd_EBTYztVhjuTFV6BwT/view?usp=share_link

**Comment by Arqui9897** [comment]
salio perfect : )
