### ISSUE TITLE
Imágenes

### ISSUE THREAD

**Issue by andres174** [gabriel12QK/movil-Ecommerce#14]
Imágenes en buena calidad para:

- Marcas
- Categorías
- Productos
- Kits

Subirlas a su respectiva carpeta en el drive del proyecto.

**Comment by Arqui9897** [comment]
ya esta todo subido a esta carpeta 
https://drive.google.com/drive/u/1/folders/1VAarbyiWsj-f0MlV7fWtaNblGG4Sx_ww
