### ISSUE TITLE
Diseño de la app repartidor

### ISSUE THREAD

**Issue by andres174** [gabriel12QK/movil-Ecommerce#16]
- Actualizar branding

**Comment by Arqui9897** [comment]
[Branding DELIGO v2.1.1.pdf](https://github.com/gabriel12QK/movil-Ecommerce/files/10436647/Branding.DELIGO.v2.1.1.pdf)

![Branding DELIGO v2 1](https://user-images.githubusercontent.com/87206394/212943462-3ceb327e-c568-40f9-aa49-00f6b7746a79.png)
