### ISSUE TITLE
Ofertas producto

### ISSUE THREAD

**Issue by andres174** [gabriel12QK/movil-Ecommerce#8]
Tomando como guía el branding disponible en la carpeta compartida de drive, crear la pagina para visualizar las OFERTAS DE PRODUCTO vigentes y activas con las funcionalidades requeridas.

https://drive.google.com/file/d/1gmLzmyjGCvgnsd_EBTYztVhjuTFV6BwT/view?usp=share_link

**Comment by bermeo2000** [comment]
Consulta
![image](https://user-images.githubusercontent.com/104100468/211224545-a044c0f6-d56d-4709-b22d-3649a065ed13.png)
imagines
![image](https://user-images.githubusercontent.com/104100468/211224556-302f9469-7c91-4439-b008-2236fc5de41a.png)
![image](https://user-images.githubusercontent.com/104100468/211224568-0cd2b94a-4f6b-4a4a-9c14-764130cda584.png)
